import { createFileRoute } from "@tanstack/react-router";
import { Instagram } from "lucide-react";
import { PageIntro } from "@/components/site-layout";
import { Button } from "@/components/ui/button";
import heroImage from "@/assets/lily-sala-clean.jpg.asset.json";
import floralImage from "@/assets/lily-cvijece-clean.jpg.asset.json";
import tableImage from "@/assets/lily-stol-clean.jpg.asset.json";

export const Route = createFileRoute("/galerija")({ head: () => ({ meta: [{ title: "Galerija vjenčanja — Lily Decor" },{ name: "description", content: "Pogledajte cvjetne dekoracije, svečane stolove i vjenčanja u izvedbi Lily Decor." },{ property: "og:title", content: "Galerija — Lily Decor" },{ property: "og:description", content: "Inspiracija iz cvijeća, svijeća i profinjenih detalja." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary_large_image" }]}), component: Gallery });
function Gallery(){return <><PageIntro eyebrow="Naši radovi" title="Galerija slavlja" text="Pogledajte dio atmosfere koju stvaramo — od intimnih cvjetnih detalja do cjelovitog uređenja svečanih prostora."/><section className="px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl gap-5 md:grid-cols-2"><img src={heroImage.url} loading="lazy" width={891} height={942} alt="Raskošno uređena svadbena sala" className="animate-soft-rise aspect-[4/3] w-full object-cover transition-transform duration-700 hover:scale-[1.01] md:col-span-2"/><img src={floralImage.url} loading="lazy" width={891} height={942} alt="Cvjetni aranžman u ružičastim tonovima" className="animate-soft-rise-delay aspect-square w-full object-cover transition-transform duration-700 hover:scale-[1.02]"/><img src={tableImage.url} loading="lazy" width={688} height={940} alt="Svečani stol s cvijećem i svijećama" className="animate-soft-rise-delay aspect-square w-full object-cover transition-transform duration-700 hover:scale-[1.02]"/></div><div className="mx-auto mt-14 max-w-2xl animate-soft-rise text-center"><h2 className="text-4xl text-brand-green">Još trenutaka na Instagramu</h2><p className="mt-3 leading-7 text-muted-foreground">Pratite naše najnovije dekoracije i pogledajte kako izgleda svaki detalj stvarnih slavlja.</p><Button asChild variant="accent" className="mt-6"><a href="https://www.instagram.com/vjencanja_lily/" target="_blank" rel="noopener noreferrer"><Instagram size={18}/>Otvori Instagram</a></Button></div></section></>}